baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 9999

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "blog.ajb.app"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show More"
    writtenBy = "Written by"
    readMore = "Read More"
    readOtherPosts = "other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    lastModDisplay = "Modified:"

    [languages.en.params.logo]
      logoText = "blog.ajb.app"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
#      [[languages.en.menu.main]]
#        identifier = "/archive"
#        name = "Archive"
#        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "https://notes.ajb.app"